baseURL = "https://jimbi-o.github.io/"
languageCode = "ja"
title = "notes on graphics programming"
theme = "PaperMod"
[[menu.main]]
identifier = 'about'
name = 'about'
url = '/about/'
weight = 10
[[menu.main]]
identifier = 'categories'
name = 'categories'
url = '/categories/'
weight = 20
[[menu.main]]
identifier = 'tags'
name = 'tags'
url = '/tags/'
weight = 30
[params]
ShowShareButtons = 'true'
ShowReadingTime = 'true'
ShowToc = 'true'
TocOpen = 'true'
ShowCodeCopyButtons = 'true'
[params.homeInfoParams]
Title = "Welcome!"
Content = "Notes on graphics programming"
[[params.socialIcons]]
name = 'twitter'
url = 'https://twitter.com/o_jimbi'
[[params.socialIcons]]
name = 'github'
url = 'https://github.com/jimbi-o'
# [[params.editPost]]
# URL = "https://github.com/jimbi-o.github.io/content"
# Text = "Suggest Changes"
# appendFilePath = true
